public class Constants {
    
    //Account
    public static final String CUSTOMER_STATUS_GOLD = 'Gold';
    public static final String CUSTOMER_STATUS_SILVER = 'Silver';
    public static final String CUSTOMER_STATUS_BRONZE = 'Bronze';
    
    // Product2
    public static final String PRODUCT_CATEGORY_CASUAL = 'Casual';
    public static final String PRODUCT_CATEGORY_SPORT = 'Sport';
    public static final String PRODUCT_MATERIAL_LEATHER = 'Leather';
    public static final String PRODUCT_MATERIAL_MATERIAL = 'Material';
    public static final String PRODUCT_CONSTRUCTION_HIGH = 'High';
    public static final String PRODUCT_CONSTRUCTION_LOW = 'Low';

    
}


